# Generated by Django 5.2.7 on 2025-10-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=512)),
                ('content', models.TextField()),
                ('github_url', models.URLField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=255)),
                ('technologies', models.ManyToManyField(to='projects.technology')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
