# Generated by Django 4.2 on 2023-08-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(default='Tagline', max_length=255),
            preserve_default=False,
        ),
    ]
