# Generated by Django 5.2.7 on 2025-10-29 18:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_project_technologies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': (django.db.models.functions.text.Lower('name'),), 'verbose_name': 'technology', 'verbose_name_plural': 'technologies'},
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
