# Generated by Django 5.2.7 on 2025-10-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_at', 'title')},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('name',)},
        ),
    ]
