# Generated by Django 5.2.7 on 2025-10-29 18:45

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': (django.db.models.functions.text.Lower('name'),)},
        ),
    ]
