# Generated by Django 5.2.7 on 2025-10-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
    ]
